
name: test
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install deps
        run: sudo apt-get update && sudo apt-get install fluidsynth ffmpeg
      - name: cloning github
        run: git clone https://github.com/ytinyui/music2midi
      - name: conda env setup
        run: cd music2midi && conda env create -f environment.yaml && conda activate music2midi
      - uses: actions/checkout@v4
      - name: downloading model
        run: wget -O model.ckpt https://github.com/ytinyui/music2midi/releases/download/0.1.0/epoch.799-step.119200.ckpt
      - run: cd ~ && python piano.py
