name: Combi Matrix
on:
  workflow_dispatch:

jobs:
  # ==============================================================================
  # JOB 1: PRE-PROCESSING (Audio Separator)
  # Menyiapkan file vokal dan instrumental untuk diproses job selanjutnya
  # ==============================================================================
  prepare_stems:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Checkout own repo
        uses: actions/checkout@v4
        with:
          path: my

      - name: Install FFmpeg
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Audio Separator
        run: |
          pip install "audio-separator[cpu]"
          # Hapus cache pip agar hemat storage
          pip cache purge

      - name: Run Audio Separator
        run: |
          mkdir audiosep_output
          audio-separator ./my/music.mp3 \
            --output_format=MP3 \
            --output_dir audiosep_output \
            --model_filename UVR-MDX-NET-Inst_HQ_4.onnx \
            --custom_output_names='{"Vocals": "vocals_output", "Drums": "drums_output", "Instrumental": "instrumental_output", "Bass": "bass_output"}'

      - name: Upload Stems Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stems-output
          path: audiosep_output

  # ==============================================================================
  # JOB 2: PROCESSING (MATRIX)
  # Menjalankan Music2Midi dan AMT secara PARALEL (Bersamaan di 2 VM berbeda)
  # ==============================================================================
  generate:
    needs: prepare_stems
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        model: [music2midi, amt] # <--- INI ADALAH MATRIXNYA

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Install FFmpeg
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Checkout own repo
        uses: actions/checkout@v4
        with:
          path: my

      - name: Download Stems
        uses: actions/download-artifact@v4
        with:
          name: stems-output
          path: audiosep_output

      # ------------------------------------------------------------------
      # LOGIKA KHUSUS: MUSIC2MIDI (Hanya jalan jika matrix == music2midi)
      # ------------------------------------------------------------------

      - name: Create requirements.txt
        if: matrix.model == 'music2midi'
        run: |
          # KITA WAJIB MEMAKSA NUMPY < 2 AGAR BASIC-PITCH TIDAK CRASH
          echo "numpy<2" > requirements.txt
          echo "basic-pitch" >> requirements.txt

      - name: Set up Python 3.10
        if: matrix.model == 'music2midi'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Installing basic pitch
        if: matrix.model == 'music2midi'
        run: |
          pip install --upgrade pip
          pip install "numpy<2"
          pip install basic-pitch[tf]
          pip install mido
      - name: running basic-pitch to convert vocals to midi
        if: matrix.model == 'music2midi'
        run: |
          basic-pitch . ./audiosep_output/vocals_output.mp3 --onset-threshold 0.7 --frame-threshold 0.5 \
            --minimum-frequency 80 --maximum-frequency 1100
          mv vocals_output_basic_pitch.mid my/vocal.mid
          python ./my/clean_piano.py ./my/vocal.mid ./my/midi.mid
      - name: Converting to mp3
        if: matrix.model == 'music2midi'
        run: |
          echo "Mendownload SoundFont Piano..."
          wget https://keymusician01.s3.amazonaws.com/FluidR3_GM.zip
          unzip FluidR3_GM.zip
          sudo apt install timidity
          timidity my/midi.mid --force-program=0 -x "soundfont FluidR3_GM.sf2" -Ow -o - | \
          ffmpeg -i - -af loudnorm -c:a libmp3lame -q:a 2 "my/audio.mp3"
      # - name: Checkout music2midi
      #   if: matrix.model == 'music2midi'
      #   uses: actions/checkout@v4
      #   with:
      #     repository: ytinyui/music2midi
      #     path: music2midi

      # - name: Setup Micromamba (Music2Midi)
      #   if: matrix.model == 'music2midi'
      #   uses: mamba-org/setup-micromamba@v2
      #   with:
      #     environment-file: music2midi/environment.yaml
      #     environment-name: music2midi
      #     cache-environment: true
      #     create-args: fluidsynth python=3.9 librosa

      # - name: Run Music2Midi Script
      #   if: matrix.model == 'music2midi'
      #   shell: bash -el {0}
      #   working-directory: ./my
      #   env:
      #     PYTHONPATH: ${{ github.workspace }}/music2midi
      #   run: |
      #     wget -O model.ckpt https://github.com/ytinyui/music2midi/releases/download/0.1.0/epoch.799-step.119200.ckpt
      #     pip uninstall -y pysoundfile soundfile
      #     pip install soundfile
          
      #     # Jalankan script (pastikan input file benar sesuai script pianocombi.py)
      #     python pianocombi.py

      # ------------------------------------------------------------------
      # LOGIKA KHUSUS: AMT (Hanya jalan jika matrix == amt)
      # ------------------------------------------------------------------
      - name: Checkout AMT
        if: matrix.model == 'amt'
        uses: actions/checkout@v4
        with:
          repository: misya11p/amt-apc
          path: amt

      - name: Run AMT Script
        if: matrix.model == 'amt'
        working-directory: ./amt/
        run: |
          sudo apt install timidity
          # Install Dependencies Heavy (Torch)
          pip install torch torchaudio torchcodec soundfile pretty-midi tqdm yt-dlp
          pip cache purge # Hemat space
          
          wget -P models/params/ https://github.com/misya11p/amt-apc/releases/download/beta/apc.pth
          
          # Proses instrumental dari artifact job sebelumnya
          python -m infer ../audiosep_output/instrumental_output.mp3
          echo "Mendownload SoundFont Piano..."
          wget https://keymusician01.s3.amazonaws.com/FluidR3_GM.zip
          unzip FluidR3_GM.zip
          timidity output.mid -x "soundfont FluidR3_GM.sf2" -Ow -o - | ffmpeg -i - -af loudnorm -acodec libmp3lame -ab 192k output.mp3

      # ------------------------------------------------------------------
      # UPLOAD HASIL (Dinamis sesuai nama matrix)
      # ------------------------------------------------------------------
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ matrix.model }}
          path: |
            my/midi.mid
            my/audio.mp3
            amt/output.mid
            amt/output.mp3
          if-no-files-found: ignore

  # ==============================================================================
  # JOB 3: COMBINE (Post-Processing)
  # Menggabungkan Vocals (Job 1) + Hasil AMT (Job 2)
  # ==============================================================================
  finalize:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Checkout own repo
        uses: actions/checkout@v4
        with:
          path: my
      # Ambil Vocals piano
      - name: Download Stems
        uses: actions/download-artifact@v4
        with:
          name: output-music2midi
          path: music2midi

      # Ambil Hasil AMT
      - name: Download AMT Output
        uses: actions/download-artifact@v4
        with:
          name: output-amt
          path: amt_result

      # Gabungkan (Sesuai logika kode asli Anda: Vocal + AMT)
      - name: Combine Audio Outputs
        run: |
          pip install pretty_midi
          python ./my/mergemidi.py --vocal ./music2midi/my/midi.mid --instr ./amt_result/amt/output.mid --max_poly 5
          echo "Mendownload SoundFont Piano..."
          wget https://keymusician01.s3.amazonaws.com/FluidR3_GM.zip
          unzip FluidR3_GM.zip
          sudo apt install timidity
          timidity final_clean.mid --force-program=0 -x "soundfont FluidR3_GM.sf2" -Ow -o - | \
          ffmpeg -i - -af loudnorm -c:a libmp3lame -q:a 2 "final_combined_output.mp3"
          # Perhatikan path inputnya disesuaikan dengan folder download artifact
          # ffmpeg -i ./music2midi/my/audio.mp3 \
          #       -i ./amt_result/amt/output.mp3 \
          #       -filter_complex "[0:a][1:a]amix=inputs=2:duration=longest" \
          #       -c:a libmp3lame -q:a 2 final_combined_output.mp3

      - name: Final Output Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Final-Combined-Output
          path: |
            final_clean.mid
            final_combined_output.mp3
